name: Validate and Tag

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Create Tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          
          # Increment the patch version
          IFS='.' read -r major minor patch <<< "${latest_tag#v}"
          new_tag="v$major.$minor.$((patch + 1))"
          
          # Create and push the new tag
          git tag $new_tag
          git push origin $new_tag
